// Decompiled with JetBrains decompiler
// Type: Microsoft.Xrm.Sdk.Query.ConditionOperator
// Assembly: Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: 6ED27353-7D93-4D8D-9CA3-2396F24E6015
// Assembly location: C:\Stas\Projects\Tricolor\To365\MyCrmRestService\Code\Decomp\Microsoft.Xrm.Sdk\Microsoft.Xrm.Sdk.dll

using System.Runtime.Serialization;

namespace Microsoft.Xrm.Sdk.Query
{
  [DataContract(Name = "ConditionOperator", Namespace = "http://schemas.microsoft.com/xrm/2011/Contracts")]
  public enum ConditionOperator
  {
    [EnumMember] Equal,
    [EnumMember] NotEqual,
    [EnumMember] GreaterThan,
    [EnumMember] LessThan,
    [EnumMember] GreaterEqual,
    [EnumMember] LessEqual,
    [EnumMember] Like,
    [EnumMember] NotLike,
    [EnumMember] In,
    [EnumMember] NotIn,
    [EnumMember] Between,
    [EnumMember] NotBetween,
    [EnumMember] Null,
    [EnumMember] NotNull,
    [EnumMember] Yesterday,
    [EnumMember] Today,
    [EnumMember] Tomorrow,
    [EnumMember] Last7Days,
    [EnumMember] Next7Days,
    [EnumMember] LastWeek,
    [EnumMember] ThisWeek,
    [EnumMember] NextWeek,
    [EnumMember] LastMonth,
    [EnumMember] ThisMonth,
    [EnumMember] NextMonth,
    [EnumMember] On,
    [EnumMember] OnOrBefore,
    [EnumMember] OnOrAfter,
    [EnumMember] LastYear,
    [EnumMember] ThisYear,
    [EnumMember] NextYear,
    [EnumMember] LastXHours,
    [EnumMember] NextXHours,
    [EnumMember] LastXDays,
    [EnumMember] NextXDays,
    [EnumMember] LastXWeeks,
    [EnumMember] NextXWeeks,
    [EnumMember] LastXMonths,
    [EnumMember] NextXMonths,
    [EnumMember] LastXYears,
    [EnumMember] NextXYears,
    [EnumMember] EqualUserId,
    [EnumMember] NotEqualUserId,
    [EnumMember] EqualBusinessId,
    [EnumMember] NotEqualBusinessId,
    [EnumMember] ChildOf,
    [EnumMember] Mask,
    [EnumMember] NotMask,
    [EnumMember] MasksSelect,
    [EnumMember] Contains,
    [EnumMember] DoesNotContain,
    [EnumMember] EqualUserLanguage,
    [EnumMember] NotOn,
    [EnumMember] OlderThanXMonths,
    [EnumMember] BeginsWith,
    [EnumMember] DoesNotBeginWith,
    [EnumMember] EndsWith,
    [EnumMember] DoesNotEndWith,
    [EnumMember] ThisFiscalYear,
    [EnumMember] ThisFiscalPeriod,
    [EnumMember] NextFiscalYear,
    [EnumMember] NextFiscalPeriod,
    [EnumMember] LastFiscalYear,
    [EnumMember] LastFiscalPeriod,
    [EnumMember] LastXFiscalYears,
    [EnumMember] LastXFiscalPeriods,
    [EnumMember] NextXFiscalYears,
    [EnumMember] NextXFiscalPeriods,
    [EnumMember] InFiscalYear,
    [EnumMember] InFiscalPeriod,
    [EnumMember] InFiscalPeriodAndYear,
    [EnumMember] InOrBeforeFiscalPeriodAndYear,
    [EnumMember] InOrAfterFiscalPeriodAndYear,
    [EnumMember] EqualUserTeams,
    [EnumMember] EqualUserOrUserTeams,
    [EnumMember] Under,
    [EnumMember] NotUnder,
    [EnumMember] UnderOrEqual,
    [EnumMember] Above,
    [EnumMember] AboveOrEqual,
    [EnumMember] EqualUserOrUserHierarchy,
    [EnumMember] EqualUserOrUserHierarchyAndTeams,
    [EnumMember] OlderThanXYears,
    [EnumMember] OlderThanXWeeks,
    [EnumMember] OlderThanXDays,
    [EnumMember] OlderThanXHours,
    [EnumMember] OlderThanXMinutes,
    [EnumMember] ContainValues,
    [EnumMember] DoesNotContainValues,
  }
}
